apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dfgdgdfgdfg
  title: Dfgdgd
  description: A static HTML website. Just like the good old days.
  links:
    - url: https://RoadieHQ.github.io/dfgdgdfgdfg/
      title: Live website
  annotations:
    github.com/project-slug: RoadieHQ/dfgdgdfgdfg
spec:
  type: website
  owner: user:dtuite
  lifecycle: experimental
